baseURL = "https://jelliott.dev/"
languageCode = "en-au"
title = "Joshua Elliott"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
[Author]
    name = "Joshua"
[params]
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/joshua-elliott/"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "Email"
        url = "mailto:joshualjelliott@gmail.com"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/freejelliott"

